=== AlexandrDrinov/task4/src/shedule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.dr.org/Shedule"
    xmlns:air="http://www.dr.org/Shedule">
    <element name="shedule">
        <complexType> 
            <sequence>           
                <element name="originDestination" type="air:OriginDestination" minOccurs="1" maxOccurs="unbounded"/>  
            </sequence>       
        </complexType>    
    </element>
    <complexType name="OriginDestination">  
        <sequence>
            <element name="departureAirport" type="string" />
            <element name="arrivalAirport" type="string" /> 
            <element name="flights" type="air:Flights" />         
        </sequence>
        <attribute name="departureDateTime" type="dateTime" use="required" />
        <attribute name="arrivalDateTime" type="dateTime" use="required" />
    </complexType>    
    <complexType name="Flights"> 
        <sequence>       
            <element name="flight" type="air:Flight" minOccurs="1" maxOccurs="unbounded" /> 
        </sequence>
    </complexType>  
    <complexType name="Flight">  
        <sequence>        
            <element name="cost" type="air:Cost"/>            
            <element name="aircraft" type="air:Aircraft"/>
        </sequence>
        <attribute name="number" type="string" use="required" />               
    </complexType> 
    <complexType name="Cost">  
        <sequence>
            <element name="firstClass" type="integer" />
            <element name="businessClass" type="integer"/>            
            <element name="economyClass" type="integer"/>
        </sequence>                 
    </complexType> 
    <complexType name="Aircraft">
        <attribute name="model" type="string" />
        <attribute name="number" type="string"/>            
        <attribute name="numberSeats" type="integer"/>                       
    </complexType>
</schema>

=== AlexandrDrinov/task4/src/shedule_result.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<air:shedule xmlns:air="http://www.dr.org/Shedule" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dr.org/Shedule shedule.xsd">
  <originDestination arrivalDateTime="2016-03-08T07:16:00.000Z" departureDateTime="2016-03-08T06:10:00.000Z">
    <departureAirport>Minsk</departureAirport>
    <arrivalAirport>Germany</arrivalAirport>
    <flights>
      <flight number="r1">
        <cost>
          <firstClass>100</firstClass>
          <businessClass>50</businessClass>
          <economyClass>20</economyClass>
        </cost>
        <aircraft model="craft1" number="b1" numberSeats="100"/>
      </flight>
      <flight number="r2">
        <cost>
          <firstClass>220</firstClass>
          <businessClass>150</businessClass>
          <economyClass>50</economyClass>
        </cost>
        <aircraft model="craft2" number="b2" numberSeats="200"/>
      </flight>
      <flight number="r3">
        <cost>
          <firstClass>300</firstClass>
          <businessClass>250</businessClass>
          <economyClass>170</economyClass>
        </cost>
        <aircraft model="craft3" number="b3" numberSeats="300"/>
      </flight>
    </flights>
  </originDestination>
  <originDestination arrivalDateTime="2016-03-10T00:16:00.000Z" departureDateTime="2016-03-09T06:10:00.000Z">
    <departureAirport>Moscow</departureAirport>
    <arrivalAirport>Paris</arrivalAirport>
    <flights>
      <flight number="r1">
        <cost>
          <firstClass>100</firstClass>
          <businessClass>50</businessClass>
          <economyClass>20</economyClass>
        </cost>
        <aircraft model="craft1" number="b1" numberSeats="100"/>
      </flight>
      <flight number="r2">
        <cost>
          <firstClass>220</firstClass>
          <businessClass>70</businessClass>
          <economyClass>20</economyClass>
        </cost>
        <aircraft model="craft2" number="b2" numberSeats="200"/>
      </flight>
      <flight number="r3">
        <cost>
          <firstClass>200</firstClass>
          <businessClass>150</businessClass>
          <economyClass>100</economyClass>
        </cost>
        <aircraft model="craft3" number="b3" numberSeats="300"/>
      </flight>
    </flights>
  </originDestination>
</air:shedule>
